const Champions = require("../models/champions")
const Items = require("../models/items")
const Traits = require("../models/traits")
const ChampionsData = require("../db/champions.json")
const ItemData = require("../db/items.json")
const TraitsData = require ("../db/traits.json")